/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CategoryId = IDL.Text;
export const ProductPic = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MerchantId = IDL.Text;
export const MerchantConfig = IDL.Record({
  'merchantName' : IDL.Text,
  'qrImagePath' : IDL.Text,
  'upiId' : IDL.Text,
  'merchantCode' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'category' : CategoryId,
  'image' : ProductPic,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
export const Credentials = IDL.Record({
  'salt' : IDL.Text,
  'hashedPassword' : IDL.Text,
});
export const OrderId = IDL.Text;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Time,
  'items' : IDL.Vec(CartItem),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, CategoryId, IDL.Text, ProductPic],
      [ProductId],
      [],
    ),
  'addRating' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrapAdmin' : IDL.Func([IDL.Nat], [], []),
  'checkout' : IDL.Func([], [], []),
  'clearAdminActivation' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteMerchantConfig' : IDL.Func([MerchantId], [], []),
  'getAllMerchantConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(MerchantId, MerchantConfig))],
      ['query'],
    ),
  'getBestSellingProduct' : IDL.Func([], [IDL.Opt(Product)], ['query']),
  'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCredentials' : IDL.Func([], [IDL.Opt(Credentials)], ['query']),
  'getMerchantConfig' : IDL.Func([MerchantId], [MerchantConfig], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductRating' : IDL.Func([ProductId], [IDL.Nat], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsFilteredByPrice' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernamePasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'resetAdminActivationCode' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMerchantConfig' : IDL.Func([MerchantId, MerchantConfig], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedStore' : IDL.Func([], [], []),
  'setCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
  'uploadProductImage' : IDL.Func([ExternalBlob], [ProductPic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CategoryId = IDL.Text;
  const ProductPic = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MerchantId = IDL.Text;
  const MerchantConfig = IDL.Record({
    'merchantName' : IDL.Text,
    'qrImagePath' : IDL.Text,
    'upiId' : IDL.Text,
    'merchantCode' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'category' : CategoryId,
    'image' : ProductPic,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  const Credentials = IDL.Record({
    'salt' : IDL.Text,
    'hashedPassword' : IDL.Text,
  });
  const OrderId = IDL.Text;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Time,
    'items' : IDL.Vec(CartItem),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, CategoryId, IDL.Text, ProductPic],
        [ProductId],
        [],
      ),
    'addRating' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrapAdmin' : IDL.Func([IDL.Nat], [], []),
    'checkout' : IDL.Func([], [], []),
    'clearAdminActivation' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteMerchantConfig' : IDL.Func([MerchantId], [], []),
    'getAllMerchantConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(MerchantId, MerchantConfig))],
        ['query'],
      ),
    'getBestSellingProduct' : IDL.Func([], [IDL.Opt(Product)], ['query']),
    'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCredentials' : IDL.Func([], [IDL.Opt(Credentials)], ['query']),
    'getMerchantConfig' : IDL.Func([MerchantId], [MerchantConfig], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductRating' : IDL.Func([ProductId], [IDL.Nat], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsFilteredByPrice' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernamePasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'resetAdminActivationCode' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMerchantConfig' : IDL.Func([MerchantId, MerchantConfig], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'seedStore' : IDL.Func([], [], []),
    'setCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [], []),
    'uploadProductImage' : IDL.Func([ExternalBlob], [ProductPic], []),
  });
};

export const init = ({ IDL }) => { return []; };