/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category { 'id' : CategoryId, 'name' : string }
export type CategoryId = string;
export interface Credentials { 'salt' : string, 'hashedPassword' : string }
export type ExternalBlob = Uint8Array;
export interface MerchantConfig {
  'merchantName' : string,
  'qrImagePath' : string,
  'upiId' : string,
  'merchantCode' : [] | [string],
}
export type MerchantId = string;
export interface Order {
  'id' : OrderId,
  'status' : string,
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Time,
  'items' : Array<CartItem>,
}
export type OrderId = string;
export interface Product {
  'id' : ProductId,
  'title' : string,
  'size' : string,
  'description' : string,
  'category' : CategoryId,
  'image' : ProductPic,
  'price' : bigint,
}
export type ProductId = string;
export type ProductPic = Uint8Array;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, CategoryId, string, ProductPic],
    ProductId
  >,
  'addRating' : ActorMethod<[ProductId, bigint], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[bigint], undefined>,
  'checkout' : ActorMethod<[], undefined>,
  'clearAdminActivation' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteMerchantConfig' : ActorMethod<[MerchantId], undefined>,
  'getAllMerchantConfigs' : ActorMethod<
    [],
    Array<[MerchantId, MerchantConfig]>
  >,
  'getBestSellingProduct' : ActorMethod<[], [] | [Product]>,
  'getCallerPrincipal' : ActorMethod<[], Principal>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCredentials' : ActorMethod<[], [] | [Credentials]>,
  'getMerchantConfig' : ActorMethod<[MerchantId], MerchantConfig>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductRating' : ActorMethod<[ProductId], bigint>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getProductsFilteredByPrice' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductsSortedByPrice' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernamePasswordSet' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'resetAdminActivationCode' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMerchantConfig' : ActorMethod<[MerchantId, MerchantConfig], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'seedStore' : ActorMethod<[], undefined>,
  'setCredentials' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, string], undefined>,
  'uploadProductImage' : ActorMethod<[ExternalBlob], ProductPic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];